---
Commands:
    Backpack:
        Permitted:
          - Admin: 0
          - Player:
          - Faction:
        NotPermitted:
          - Playfield:
          -  Faction:
          -  Player:
        UsageCost: 0

    Find:
        Permitted:
          - Admin: 3
          - Player:
          - Faction:
        NotPermitted:
          - Playfield:
          -  Faction:
          -  Player:
        UsageCost: 0

    Inbox:
        Permitted:
          - Admin: 0
          - Player:
          - Faction:
        NotPermitted:
          - Playfield:
          -  Faction:
          -  Player:
        UsageCost: 0

    Send:
        Permitted:
          - Admin: 0
          - Player:
          - Faction:
        NotPermitted:
          - Playfield:
          -  Faction:
          -  Player:
        UsageCost: 0
