JumpGates:
  - Playfield: "Akua Orbit"
    JumpGatePOI: 123456
    Departure:
      - X: 150.0
        Y: 150.0
        Z: 0.0
        Radius: 2000
    ToPlayfield: "Omicron Orbit"
    Destination:
     - Position:
        X: 150.0
        Y: 150.0
        Z: 0.0
     - Rotation:
        X: 0.0
        Y: 0.0
        Z: 0.0

